#!/bin/bash

if [ -z "$MOZ_FETCHES_DIR" ]; then
  export MOZ_FETCHES_DIR=/builds/worker/fetches
fi
if [ -z "$INCLUDE" ]; then
  export INCLUDE=".:$MOZ_FETCHES_DIR/vs/VC/Tools/MSVC/14.50.35717/atlmfc/include:$MOZ_FETCHES_DIR/vs/VC/Tools/MSVC/14.50.35717/include"
fi
if [ -z "$CLANG_PATH" ]; then
  export CLANG_PATH=$MOZ_FETCHES_DIR/clang
  export PATH=$CLANG_PATH/bin:$PATH
fi
make $@